### ISSUE TITLE
Error while trying to test on loopback.

### ISSUE THREAD

**Issue by theSage21** [anilshanbhag/videochat#1]
```
ghost@amnesia ~/dev/videochat $ python server.py 
server
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
TCPServer Waiting for client on port 5000
I got a connection from  ('127.0.0.1', 42707)
Traceback (most recent call last):
  File "server.py", line 31, in <module>
    server.start()
  File "server.py", line 23, in start
    frame = vsock.vreceive()
  File "/home/ghost/dev/videochat/videosocket.py", line 46, in vreceive
    raise RuntimeError("Socket connection broken")
RuntimeError: Socket connection broken
ghost@amnesia ~/dev/videochat $ 
```

```
ghost@amnesia ~/dev/videochat $ python client.py 
client
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
libv4l2: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl S_FMT
libv4l2: error setting pixformat: Device or resource busy
libv4l1: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT

OpenCV Error: Bad argument (Array should be CvMat or IplImage) in cvGetSize, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp, line 1238
Traceback (most recent call last):
  File "client.py", line 34, in <module>
    client.connect()
  File "client.py", line 19, in connect
    frame = self.videofeed.get_frame()
  File "/home/ghost/dev/videochat/videofeed.py", line 25, in get_frame
    jpegImg = Image.fromstring("RGB", cv.GetSize(self.frame), self.frame.tostring())
cv2.error: Array should be CvMat or IplImage
ghost@amnesia ~/dev/videochat $ 
```

I am at my wits end. Can you help?

**Comment by anilshanbhag** [comment]
Thanks for reporting. Its been a while since I looked at the code. Will try to get it working later tonight and let you know.

**Comment by theSage21** [comment]
This might be relevant, I think.
http://stackoverflow.com/questions/5140230/opencv-array-should-be-cvmat-or-iplimage-releasing-a-capture-object

**Comment by anilshanbhag** [comment]
Can you try again ? Things are working now. 
Feel free to reopen if things don't work.

**Comment by theSage21** [comment]
Oh I fixed this. I was trying to capture the same camera twice. Hence the issue. Thanks
