### ISSUE TITLE
Error on OSX: OpenCV Error: Unspecified error

### ISSUE THREAD

**Issue by megrimm** [anilshanbhag/videochat#4]
i get:

Connecting to 127.0.0.1....
client
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvWaitKey, file /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp, line 654
Traceback (most recent call last):
  File "client.py", line 28, in <module>
    client.connect()
  File "client.py", line 16, in connect
    frame=self.videofeed.get_frame()
  File "/Users/megrimm/Desktop/videochat-master/videofeed.py", line 17, in get_frame
    c = cv2.waitKey(1)
cv2.error: /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:654: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvWaitKey

**Comment by aviralgoyal1997** [comment]
I think this is due to wrong installed opencv,first you should check if ur opencv is working fine or not by simply opening a webcam by cv2.videocapture,if u get error then there is definitely problem of codec (opencv_ffmpeg244.dll) is missing.
